# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anne-Sophie Sevens
email: annesophie_sevens@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Created by Benoît Sevens
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.annesophiesevens.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

t:
  en:
    biography:
      name: "Biography"
      url: "/biography-en.html"
    repertoire:
      name: "Repertoire"
      url: "/repertoire-en.html"
    pictures:
      name: "Pictures"
      url: "/pictures-en.html"
    audio:
      name: "Audio"
      url: "/audio-en.html"
    video:
      name: "Video"
      url: "/video-en.html"
    events:
      name: "Events"
      url: "/events-en.html"
  fr:
    biography:
      name: "Biographie"
      url: "/biography-fr.html"
    repertoire:
      name: "Répertoire"
      url: "/repertoire-fr.html"
    pictures:
      name: "Photos"
      url: "/pictures-fr.html"
    audio:
      name: "Audio"
      url: "/audio-fr.html"
    video:
      name: "Vidéo"
      url: "/video-fr.html"
    events:
      name: "Evènement"
      url: "/events-fr.html"

